### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by cristianfb1989** [marius-h/flutter_enhancement_suite#1]
Hello good night, how can I install the plugin? Android Studio does not allow me. Thank you!
![2019-08-03_22-13-06](https://user-images.githubusercontent.com/16965222/62418296-0c2bc980-b63c-11e9-8e33-3ee0763a519d.png)

**Comment by GregorySech** [comment]
Same happened for me, after installing the beta version of Android Studio (3.5 RC2) it appearedon the search.

**Comment by marius-h** [comment]
Thanks for pointing that out. I addressed the issue in the latest version (v1.1.2) which should roll out in a few days. If you want to try out right now you can do so by downloading the [zip-archive](https://github.com/marius-h/flutter_enhancement_suite/releases/tag/v1.1.2) and install it by choosing the "Install plugin from disk" option and selecting the zip-archive. Please let me know if that fixed your issue with installing the plugin. 

Have fun coding \o

**Comment by ride4sun** [comment]
I tried to install from disk  but I get an error message  -> 
Plugin 'Flutter Enhancement Suite' is incompatible with this installation'

**Comment by marius-h** [comment]
@ride4sun What version of Android Studio are you using?

**Comment by ride4sun** [comment]
3.4.2

**Comment by marius-h** [comment]
Huh I was able to install the plugin without any issues in Android Studio 3.4.2. Have you already tried installing the latest version? https://github.com/marius-h/flutter_enhancement_suite/releases/tag/v1.1.3

**Comment by cristianfb1989** [comment]
@marius-h 

It's working!
![0ZcmCbrLqq](https://user-images.githubusercontent.com/16965222/62713699-8e691480-b9d3-11e9-9538-a2a874991da2.png)

Thank you very much for your recommendation!
