### ISSUE TITLE
Add more snippets

### ISSUE THREAD

**Issue by ericklhe** [marius-h/flutter_enhancement_suite#10]
It'll be excellent if we have snippets for main, for, if, switch, while just like the dart/flutter plugin on vscode.

main:
![image](https://user-images.githubusercontent.com/16799511/63643601-46701000-c6aa-11e9-8e56-25da919feaff.png)

if: 
![image](https://user-images.githubusercontent.com/16799511/63643581-ae722680-c6a9-11e9-8c15-577e118d43f1.png)

for:
![image](https://user-images.githubusercontent.com/16799511/63643595-158fdb00-c6aa-11e9-80a6-cad2e56175b7.png)

Regards,

**Comment by ericklhe** [comment]
switch:
![image](https://user-images.githubusercontent.com/16799511/63643610-7cad8f80-c6aa-11e9-8efe-257a2bc79218.png)

**Comment by marius-h** [comment]
Added "switch case", "if", "if else" & "main" to the snippets. The loops are already available through the Dart/Flutter plugin ("itar", "iter")

**Comment by ericklhe** [comment]
Where can I find these snippets? I don't see it in the snippet's page.

**Comment by marius-h** [comment]
You mean the snippets which I've added? Those will be available in the next update which I'm currently still working on

**Comment by ericklhe** [comment]
My bad. Sorry, hehe.
