### ISSUE TITLE
[bug] coverage highlight not consistent with Codecov

### ISSUE THREAD

**Issue by mzdm** [marius-h/flutter_enhancement_suite#103]
Hey, thanks for the great plugin. I'm loving the code coverage.

There's one minor bug I've encountered. That the coverage highlight is not sometimes(?) highlighting correctly.

Actual:
![image](https://user-images.githubusercontent.com/67197047/113484752-46510c80-94aa-11eb-8190-f310930b1b61.png)

Expected - Codecov:
https://codecov.io/gh/mzdm/iso_duration_parser/src/master/lib/src/parser.dart
![image](https://user-images.githubusercontent.com/67197047/113484761-510ba180-94aa-11eb-9e7d-f6dfd60e45b6.png)

IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021
Licensed to Matěj Žídek
Subscription is active until November 9, 2021.
For educational use only.
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1974M
Cores: 12
Non-Bundled Plugins: com.bloc.intellij_generator_plugin, Dart, org.jetbrains.kotlin, io.flutter, de.mariushoefler.flutter_enhancement_suite, Pythonid

**Comment by mzdm** [comment]
Just tried it again today and it highlighted correctly. Probably a random bug.

**Comment by lenarmazitov** [comment]
For me code coverage correctly works only when I first time run test on directory.
Then I make changes to test, run test with coverage again and expect to see coverage % is changed, but it remains same.

I can achieve coverage to change only when I delete test configuration for directory, recreate it and run with coverage.
