### ISSUE TITLE
Quick actions to open package pages on pub.dev

### ISSUE THREAD

**Issue by ekuleshov** [marius-h/flutter_enhancement_suite#121]
**Describe the use-cases of your feature**

When plugin shows version updated in pubspec.yaml it tells the version number, but not the information on what been changed in the package.

**Describe your solution**

It would be great to have some additional options in the Alt-Enter context menu in addition to "Update Package". For example open the package info page on pub.dev website and open package changelog. E.g. using the following urls and default web browser as configured in IDEA to allow quickly navigate there:

`https://pub.dev/packages/{package name}`
`https://pub.dev/packages/{package name}/changelog`

**Comment by marius-h** [comment]
![image](https://user-images.githubusercontent.com/29115214/130278439-f0528c8c-5bff-4e30-b512-7c25b5f2b5b5.png)

**Comment by ekuleshov** [comment]
Thank you. Is plugin update coming soon?

**Comment by marius-h** [comment]
Yep. Maybe next week but I can't make any promises yet
