### ISSUE TITLE
Extract widget to new file

### ISSUE THREAD

**Issue by Solido** [marius-h/flutter_enhancement_suite#13]
When starting a new project I use the extract to widget often but I'd like to be able to move the declaration easily to a new file when it's detailed enough.
Currently I've to create a new file and copy - paste.
Thanks !

**Comment by marius-h** [comment]
Unfortunately I had to implement this feature in a rather hacky way as the Dart plugin relies on server-sided formatting which I cannot change with my plugin. If you see any weird bugs when trying out this feature in the upcoming version, please let me know.
