### ISSUE TITLE
Add configuration to remove BLoC from UI

### ISSUE THREAD

**Issue by ZanSchaffer** [marius-h/flutter_enhancement_suite#144]
Add a settings page where I can disable
Right click on project tree > New > Flutter Bloc

I think it creates some confusion in a plugin that shouldn't care about state management and duplicates functionality when using the bloc plugin.

![image](https://user-images.githubusercontent.com/17552572/130196317-ef17945b-1b66-4db9-ad78-8b805af36351.png)

**Comment by marius-h** [comment]
Already removed in #142. Will be fixed in v1.6.0
