### ISSUE TITLE
New version available is incorrectly reported

### ISSUE THREAD

**Issue by ekuleshov** [marius-h/flutter_enhancement_suite#189]
**Describe the bug**

Plugin incorrectly reports "new version" available when semantically higher version is already used. E.g. `0.9.4+10` vs `0.9.4+9`.

**Steps to Reproduce**

In the pubspec.yaml mouse over on reported plugin version and observe popup shown below

**Expected behavior**

Versions should be compares semantically instead of textually, so `+10` is higher than `+9`.

**Screenshots**

![image](https://user-images.githubusercontent.com/440954/152466127-8298bf63-33cb-4490-ac62-ee2c5911cc3c.png)

**Software used**

```
Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
Non-Bundled Plugins: Dart (211.7798), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), io.flutter (63.2.2), de.mariushoefler.flutter_enhancement_suite (1.6.0), org.intellij.plugins.markdown (211.7142.37)
```

**Additional context**

n/a

**Comment by marius-h** [comment]
Fixed in v1.6.1 ✅
