### ISSUE TITLE
"make camelCase" and "make UPPER_CASE" actions

### ISSUE THREAD

**Issue by ekuleshov** [marius-h/flutter_enhancement_suite#195]
**Describe the use-cases of your feature**

The plugin has a really handy "make private" and "make public" actions available on alt-Enter.
It also would be really handy to have "make camelCase" and "make UPPER_CASE" that would help to rename a field in accordance to recommended lint options https://dart-lang.github.io/linter/lints/constant_identifier_names.html

**Describe your solution**

**Comment by marius-h** [comment]
IMO this is something which should be implemented in the[ Dart language server](https://github.com/dart-lang/sdk/issues) as this option should be linked to the lint options. This approach would also have the advantage that it would work with `dart fix`.
