### ISSUE TITLE
How to disable automatically run "pub get" when auto-completing or updating a package?

### ISSUE THREAD

**Issue by dungnv2602** [marius-h/flutter_enhancement_suite#21]
Like title, I find this really annoying when update more than 1 package. How to disable this feature?

**Comment by marius-h** [comment]
Currently, there is no way of deactivating the "pub get"-automation. Do you have any suggestions of how you'd like it to be implemented in the next version?

**Comment by dungnv2602** [comment]
Right now, using your packages. I usually felt into packages lock sequence, that means I have to wait for 'packages get' command run successfully before updating another one, and repeat again and again. It's time consuming.

Before using this package, I used the one named 'Flutter Pub Version Checker'. It basically let me update one or more packages version, that's all, And then I will run command 'packages get' my self.
I find this more comfortable for me in cases which I want to update multiple packages.

**Comment by marius-h** [comment]
Will be fixed in the next update 😉 

![image](https://user-images.githubusercontent.com/29115214/71758279-e3835680-2e9d-11ea-986e-01b58614e050.png)
