### ISSUE TITLE
Code coverage 

### ISSUE THREAD

**Issue by sebastianhaberey** [marius-h/flutter_enhancement_suite#212]
Hi @marius-h,

I saw that you removed code coverage. I'd been using your plugin last year and I really liked that feature. Any chance of code coverage reappearing? Cheers,

Sebastian

**Comment by marius-h** [comment]
Hey Sebastian!

Glad you liked the feature! Unfortunately I had to remove the feature from my plugin as the developers of the official Flutter plugin for IntelliJ copied my code (without crediting me). As there was suddenly the same feature in two different plugins, I had to remove it from my plugin. However, you should be able to use the feature when using the official Flutter plugin now. 

Cheers, Marius 😄

**Comment by sebastianhaberey** [comment]
Welp. That's not very nice. A credit wouldn't hurt anyone. 

Anyways, thanks for implementing it, even if it lives somewhere else now!
