### ISSUE TITLE
Package Material Design Icons

### ISSUE THREAD

**Issue by StefanLobbenmeier** [marius-h/flutter_enhancement_suite#23]
I just stumbled upon this Plugin and from what I could see so far it could be used to solve this issue in a Dart package: https://github.com/ziofat/material_design_icons_flutter/issues/7

Can this Plugin be extended to also include icon support for material_design_icons_flutter?

**Describe your solution**

I am not sure if it is as easy as just adding another icon pack or if there is also some generation logic that has to be touched.

**Comment by StefanLobbenmeier** [comment]
It looks like material_design_icons uses basically the same approach as the flutter_vector_icons library that you support - so adding support should actually be easy. However it seems that the material_design_icons are actually a subset of flutter_vector_icons, so I am not sure if it actually even makes sense to persue this. 

I will check with material_design_icons owner what he thinks about this.

**Comment by marius-h** [comment]
If you mean [this](https://pub.dev/packages/material_design_icons_flutter) package, it should be possible to add support for this package to the plugin. As I want to keep the plugin's download size reasonably small, I decided against adding hundreds of icon packages but - as far as I can tell - both packages use the same icons so implementing that shouldn't be an issue.

**Comment by marius-h** [comment]
Done 🥳

![image](https://user-images.githubusercontent.com/29115214/67809154-7f58a680-fa98-11e9-9c4a-6fc25a7b35d6.png)

![image](https://user-images.githubusercontent.com/29115214/67809224-9a2b1b00-fa98-11e9-97fe-afef16928b5c.png)
