### ISSUE TITLE
Plugin breaks syntax highlighting

### ISSUE THREAD

**Issue by cirediew** [marius-h/flutter_enhancement_suite#233]
I found out that this plugin can break the Dart syntax highlighting when using an icon package.

I issued my [original issue](https://github.com/dart-lang/sdk/issues/50328) in the dart-lang repo before figuring out it was this plugin that caused the issue.

Disabling the plugin fixes the issue.

**Comment by marius-h** [comment]
I could not reproduce the issue on the latest version. Feel free to reopen the ticket if it still occurs after manually installing the latest preview version of the plugin here 
--> [Flutter Enhancement Suite-1.7.0.zip](https://github.com/marius-h/flutter_enhancement_suite/files/12499679/Flutter.Enhancement.Suite-1.7.0.zip) <--
