### ISSUE TITLE
Please add "subj" shortcut as in AFS

### ISSUE THREAD

**Issue by bDev10** [marius-h/flutter_enhancement_suite#24]
Thank you for your plugin.
It would be great if you could add a "subj" shortcut like in [Awesome Flutter Snippets](https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets).
You may also check for other good snippets in AFS.

**Comment by marius-h** [comment]
Thanks for your suggestion! I'll happily have a look at the snippets of AFS to see which ones I might implement. Happy coding! 😄
