### ISSUE TITLE
I cannot figure out how to use the snippets

### ISSUE THREAD

**Issue by d-silveira** [marius-h/flutter_enhancement_suite#32]
Please help, I cannot figure out how to use any of your provided snippets! May it be a conflict with Flutter Snippets which I also have installed?
Or am I doing something wrong, I'm just typing the alias in an editor window and waiting for the respective snippet to show up as a suggestion, but it didn't work. Tried several from the docs. Also tried to ctrl+J and then typing, also no luck.

Regards

**Comment by marius-h** [comment]
Do they show up in your live templates settings?

**Comment by rlfolden** [comment]
I have the same problem and none of the fxxxxxx snippets do not show up in live template settings.  i am using Android Studio 3.6.2

**Comment by marius-h** [comment]
@d-silveira @rlfolden Are the snippets still not working for you?

**Comment by marius-h** [comment]
Feel free to reopen this ticket if snippets are still not working for you :)
