### ISSUE TITLE
[Feature] Display package description onHover

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [marius-h/flutter_enhancement_suite#38]
**Describe the use-cases of your feature**

When deciding which package to use, it would be nice to know what the package does by hovering over it or through a menu.

Maybe here, where it says null | object | string
<img width="465" alt="Screen Shot 2020-03-12 at 11 36 50 AM" src="https://user-images.githubusercontent.com/23037821/76555937-d5c9ee80-6455-11ea-979b-9d7c0d55941c.png">

**Comment by marius-h** [comment]
I've actually already implemented that feature but a bug in IntelliJ requires you to follow these steps for it to work:
1. Open settings
2. Go to "Languages & Frameworks > Schemas and DTDs > Remote JSON Schemas"
3. Uncheck the box "Allow downloading JSON Schemas from remote sources"
4. Restart IntelliJ

After that you can hover over the dependency and press F1 on Mac or Ctrl+Q on Windows/Linux to open the package's documentation.

**Comment by ThinkDigitalSoftware** [comment]
Ok. I already had that enabled but it shows the same info as in the screenshot.
