### ISSUE TITLE
V 1.3.2 is not up to date.

### ISSUE THREAD

**Issue by eikob** [marius-h/flutter_enhancement_suite#46]
It seems the recently "published" version of 1.3.2 missed a version bump to 1.3.3 or so.

I already had 1.3.2. installed on my machine (with the Bloc bug), and I cannot update. Also, deinstalling and reinstalling 1.3.2 seems to get the "old" version with the bug.

**Comment by eikob** [comment]
Also check out https://plugins.jetbrains.com/plugin/12693-flutter-enhancement-suite/versions
1.3.2 had been published on January 07th already... probably not from this repo. 🧐

**Comment by marius-h** [comment]
Yeah I actually messed up while rushing through releasing the update at 3am. It looks like I forgot to push the changes of the already published v1.3.2 to GitHub. I'll try my very best to release the correct update later today.
