### ISSUE TITLE
pubspec.yaml ctrl-Q doesn't pull up package documentation

### ISSUE THREAD

**Issue by wayne-werner** [marius-h/flutter_enhancement_suite#50]
**Describe the bug**
When pressing ctrl-Q, the following pops up when pressing ctrl-Q on a package:
```
freezed_annotation: null | object | string
Version range of the package or SDK to use
```
This appears to be some sort of help for the yaml file structure.  I can't really say how long ago, several months, but at one time ctrl-Q did indeed produce package documentation when pressed.

**Screenshots**

![nodoc](https://user-images.githubusercontent.com/4612165/79901092-47924200-83dd-11ea-9624-91310114f967.png)

**Software used**
```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to Wayne Werner
Subscription is active until January 9, 2021
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1973M
Cores: 8
Registry: ide.editor.tabs.open.at.the.end=true, debugger.watches.in.variables=false, ide.tooltip.initialDelay=1003
Non-Bundled Plugins: Mongo Plugin, com.bloc.intellij_generator_plugin, com.jetbrains.plugins.ini4idea, com.zll.format, Pythonid, Dart, io.flutter, org.jetbrains.kotlin, org.intellij.scala, de.mariushoefler.flutter_enhancement_suite, com.intellij.plugins.html.instantEditing, com.jetbrains.plugins.jade, com.dmarcotte.handlebars```

**Comment by marius-h** [comment]
Unfortunately, there's a bug in IntelliJ which requires you to follow these steps for it to work:

    Open settings
    Go to "Languages & Frameworks > Schemas and DTDs > Remote JSON Schemas"
    Uncheck the box "Allow downloading JSON Schemas from remote sources"
    Restart IntelliJ

After that you can hover over the dependency and press F1 on Mac or Ctrl+Q on Windows/Linux to open the package's documentation.

**Comment by wayne-werner** [comment]
Thanks, Marius!
It works now... interestingly, and I don't know if this is intended or not, but hovering over the version number, instead of the package name fails to get documentation.

Anyhow, thanks for the fix, the documentation fetch is an awesomely nice feature!  Thanks for your good work!

Wayne

**Comment by marius-h** [comment]
Glad I could help you! It's actually intended that you don't get to the documentation when hovering over the version number. I'm planning on implementing a changelog viewer which would show up when hovering over the version number :)

**Comment by wayne-werner** [comment]
Oh, that's nice!  Thanks again.
