### ISSUE TITLE
Is the dependency to the official flutter plugin really needed  

### ISSUE THREAD

**Issue by long1eu** [marius-h/flutter_enhancement_suite#59]
Right now I'm using this plugin https://plugins.jetbrains.com/plugin/14718-fluterstorm instead of the official one. To be able to use the Flutter Storm I need to disable the official plugin. You plugin depends on the official one. Is it possible to remove the dependency on it and maybe just copy the methods? 

Thanks.

Please charge for this plugin.

**Comment by marius-h** [comment]
Hey there! :) Unfortunately the Flutter dependency is needed for several features. I could maybe make the Flutter dependency optional but this would also remove several features for people who haven't installed the Flutter plugin yet. If you have any idea on how I could fix this issue, let me know. I will happily implement it.

Regarding charging for this plugin: I decided against that as I also want to support Flutter developers who are just getting started with Flutter as well as people who might not have enough money to spend on things like plugins.
Therefore, I created options to support the development of this plugin via donations 😄
