### ISSUE TITLE
PubSpec library link to pub.dev

### ISSUE THREAD

**Issue by Solido** [marius-h/flutter_enhancement_suite#6]
Suggestion

Ctrl or Option key + click on a lib name drives you to pub.spec online page to consult the docs

**Comment by marius-h** [comment]
I actually had the same idea yesterday. I've already been looking into ways on how to implement this feature. The easiest approach would probably be pressing alt+enter and then having an option like "show plugin's documentation".

**Comment by Solido** [comment]
The common shortcut is to use code exploration to trigger the link but if it's too complicated a menu will do it ! 
I'm really using your plugin so I may often come with ideas or concept your working on which kinda validate the concept since many people get the evidence :)

**Comment by marius-h** [comment]
Which of the following implementations do you prefer?
1. Show plugin's README if available <br>
![image](https://user-images.githubusercontent.com/29115214/63217418-8e40e580-c146-11e9-9f14-bdce5cc8f0ee.png)

2. Show plugin's description and a link to its documentation <br>
![image](https://user-images.githubusercontent.com/29115214/63217454-1aeba380-c147-11e9-97cf-85540c364389.png)

**Comment by Solido** [comment]
The use case is we want to see the docs because we're looking for details and exemple.
So I'd go with the first solution.

What's yours ?

**Comment by marius-h** [comment]
I'm actually considering to use both. The first one would show up by pressing Ctrl+Q on the pub package and the second one would be displayed next to the package auto-completion like so: <br> 
![image](https://user-images.githubusercontent.com/29115214/63218189-1e3a5b80-c156-11e9-83c4-7c45e16bb5d2.png)

**Comment by Solido** [comment]
Oh you're right I forgot about the live search result.
