### ISSUE TITLE
Plugin updates are suggested from Preview channel

### ISSUE THREAD

**Issue by pazhut** [marius-h/flutter_enhancement_suite#77]
looking at the pubspec.yaml file of my project i see some plugins mark as yellow - meaning there is available update. when looking into the suggested version is show the preview one not the latest.

for example:
google_fonts: ^1.1.1 -> suggested is 2.0.0 while latest is 1.1.2

please provide guidelines as how to fix this

Thanks much

**Comment by marius-h** [comment]
As far as I can tell the plugin isn't picking release-versions from the stable channel only which is why it is showing you to update to ^2.0.0
I will fix this in v1.4.1 :)

(For reference) https://pub.dev/packages/google_fonts/versions

**Comment by pazhut** [comment]
Thanks much

**Comment by pazhut** [comment]
Hi

I assume we're supposed to see an update to the plugin soon?

Paz
